version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: myweb-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: spring
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - myweb-network
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    # build: ./backend
    image: ${DOCKER_USERNAME}/myweb-backend:latest
    container_name: myweb-backend
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://db:3306/spring?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      DB_USERNAME: root
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - myweb-network

  frontend:
    # build: ./frontend
    image: ${DOCKER_USERNAME}/myweb-frontend:latest
    container_name: myweb-frontend
    ports:
      - "80:80"
    networks:
      - myweb-network

networks:
  myweb-network:
    driver: bridge

volumes:
  db_data: