name: CI/CD Pipeline

on:
  push:
    branches: [ "main", "develop", "feature/ci-cd" ]

jobs:
  # === 1. 백엔드 빌드 및 푸시 ===
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v4

      - name: JDK 21 설정
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Create Firebase Key File
        run: |
          mkdir -p ./backend/src/main/resources
          echo "${{ secrets.FIREBASE_KEY_BASE64 }}" | base64 --decode > ./backend/src/main/resources/serviceAccountKey.json

      # Gradle 권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x ./backend/gradlew

      # Docker Buildx 설정
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Docker Hub 로그인
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 백엔드 이미지 빌드 및 푸시
      - name: Build and push Backend Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/myweb-backend:latest

  # === 2. 프론트엔드 빌드 및 푸시 ===
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v4

      - name: Create Frontend Env File
        run: |
          echo "${{ secrets.FRONTEND_ENV_BASE64 }}" | base64 --decode > ./frontend/.env

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 프론트엔드 이미지 빌드 및 푸시
      - name: Build and push Frontend Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/myweb-frontend:latest